import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    // // But you can create a sidebar manually
    // tutorialSidebar: [
    //     "intro",
    //     "hello",
    //     {
    //         type: "category",
    //         label: "Tutorial",
    //         items: ["tutorial-basics/create-a-document"],
    //     },
    // ],

    // key 对应顶部栏
    // "header-bar1": [
    //     {
    //         type: "autogenerated", // 根据文件夹内容自动生成，推荐这个配置
    //         dirName: "new-tab1",
    //     },
    // ],
    // "bar-id-prog": [
    //     {
    //         type: "autogenerated",
    //         dirName: "program",
    //     },
    // ],
};

export default sidebars;
