name: docsearch

on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Run algolia/docsearch-scraper image
          env:
            ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
            ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          run: |
            docker run \
            --env APPLICATION_ID=${ALGOLIA_APP_ID} \
            --env API_KEY=${ALGOLIA_API_KEY} \
            algolia/docsearch-scraper
